elasticsearch:
  - host: es-dev-data01.sgdctroy.net
    port: 9200
    scheme: http
  - host: es-dev-data02.sgdctroy.net
    port: 9200
    scheme: http
  - host: es-dev-data03.sgdctroy.net
    port: 9200
    scheme: http
  index: boards-crawl-logs-*