elasticsearch_hosts:
  - scheme: http
    host: es-dev-data01.sgdctroy.net
    port: 9200
  - scheme: https
    host: es-dev-data01.sgdctroy.net
    port: 9200
  - scheme: https
    host: es-dev-data01.sgdctroy.net
    port: 9200
index: boards-crawl-logs-*
